### ISSUE TITLE
Ругань Instagramm на ссылку

### ISSUE THREAD

**Issue by iCCupPlatoon** [tgrm/tgrm.github.io#4]
Не дает отправить сгенеренную ссылку в директе, ругается. Возможно починить?

**Comment by Taraflex** [comment]
@iCCupPlatoon Подскажите пожалуйста такому пещерному человеку как я, "в директе" это где?

**Comment by iCCupPlatoon** [comment]
> @iCCupPlatoon Подскажите пожалуйста такому пещерному человеку как я, "в директе" это где?

Личные сообщения в инстаграмм.

**Comment by Taraflex** [comment]
Невозможно пофиксить, так как редирект идет через 404 страницу.
